name: Daily Github-Trending
run-name: ${{ github.actor }} is collecting Github-Trending 🚀
on: [push]
  # schedule:
  #   # UTC time 1:00AM every weekday
  #   - cron: "0 1 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r trending/requirements.txt

    - name: Run Scraper
      run: |
        python trending/scraper.py

    # Runs a set of commands using the runners shell
    - name: Make commit
      run: |
        echo start push
        git config --global user.name "introverti"
        git config --global user.email "x523356708@gamil.com"
        git add github_trending/
        git commit -m $(date +%d-%m-%Y)

    # - name: Set output variables
    #   id: vars
    #   run: |
    #       pr_title="[Daily] Github-Trending $(date +%d-%m-%Y)"
    #       pr_msg="This PR was auto-generated on $(date +%d-%m-%Y) \
    #         by [create-pull-request](https://github.com/peter-evans/create-pull-request)."
    #       echo "pr_title=$pr_title" >> $GITHUB_OUTPUT
    #       echo "pr_msg=$pr_msg" >> $GITHUB_OUTPUT

    # - name: Create Pull Request
    #   uses: peter-evans/create-pull-request@v5.0.2
    #   with:
    #     title: ${{ steps.vars.outputs.pr_title }}
    #     commit-message: ${{ steps.vars.outputs.pr_msg }}
    #     token: ${{ secrets.MY_PAT_TOKEN  }}


    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.MY_PAT_TOKEN  }}
        branch: main
