name: Innovusion Weekly Report
run-name: ${{ github.actor }} is generating Innovusion Weekly Report 🚀
on: [push]
  # schedule:
  #   # UTC time 1:00AM every weekday
  #   - cron: "0 1 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python 3.10.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.10
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r trending/requirements.txt

    - name: Run Scraper
      run: |
        python weekly/scraper.py
